"""updated profile fields

Revision ID: 0418146121a4
Revises: a19bafa07fa5
Create Date: 2026-06-09 19:17:15.823634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0418146121a4'
down_revision: Union[str, Sequence[str], None] = 'a19bafa07fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    profile_status_enum = sa.Enum(
        'active', 
        'inactive', 
        'archived', 
        'disabled', 
        name='profile_status'
        )
    
    profile_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('profiles', sa.Column('profile_status', profile_status_enum, nullable=False, server_default='active'))
    op.alter_column('profiles', 'profile_status', server_default=None)
    op.add_column('profiles', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.drop_column('profiles', 'is_active')
    op.drop_column('profiles', 'website_url')
    op.drop_column('profiles', 'instagram_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('instagram_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('website_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'profile_image_url')
    op.drop_column('profiles', 'profile_status')
    # ### end Alembic commands ###
