"""Added card code

Revision ID: 1723f13e9261
Revises: 1ccdd1eb9050
Create Date: 2026-05-08 19:40:39.511608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1723f13e9261'
down_revision: Union[str, Sequence[str], None] = '1ccdd1eb9050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_code', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'cards', ['card_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_column('cards', 'card_code')
    # ### end Alembic commands ###
