"""Allow inactive cards

Revision ID: 1ccdd1eb9050
Revises: cfd4621e828d
Create Date: 2026-05-08 19:34:55.613688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccdd1eb9050'
down_revision: Union[str, Sequence[str], None] = 'cfd4621e828d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
