"""add resume_url to profiles

Revision ID: 1cfb283173b2
Revises: 8da44ee1eb08
Create Date: 2026-09-18 02:25:06.352079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfb283173b2'
down_revision: Union[str, Sequence[str], None] = '8da44ee1eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('resume_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'resume_url')
    # ### end Alembic commands ###
