"""add supabase_auth_id to users

Revision ID: 287b4623f7ac
Revises: 1cfb283173b2
Create Date: 2026-10-08 13:51:52.735581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287b4623f7ac'
down_revision: Union[str, Sequence[str], None] = '1cfb283173b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_auth_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_users_supabase_auth_id', 'users', ['supabase_auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_supabase_auth_id', 'users', type_='unique')
    op.drop_column('users', 'supabase_auth_id')
    # ### end Alembic commands ###
