"""adjusted profile and card models to allow non assigned cards

Revision ID: 4cd8f36f8fe4
Revises: 1de4df3fa93b
Create Date: 2026-05-16 20:01:21.218932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd8f36f8fe4'
down_revision: Union[str, Sequence[str], None] = '1de4df3fa93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_profile_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'profiles', ['profile_id'], ['profile_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_profile_id_fkey'), 'cards', 'profiles', ['profile_id'], ['profile_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
