"""add display order to profiles

Revision ID: 541b87bf0083
Revises: 9b8965988c5d
Create Date: 2026-06-26 13:02:31.782365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541b87bf0083'
down_revision: Union[str, Sequence[str], None] = '9b8965988c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    
    op.alter_column("profiles", "display_order", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'display_order')
    # ### end Alembic commands ###
