"""added card_tap model for analytics

Revision ID: 55e81778f966
Revises: 7738c736319c
Create Date: 2026-05-09 03:53:13.765915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e81778f966'
down_revision: Union[str, Sequence[str], None] = '7738c736319c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_taps',
    sa.Column('tap_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tap_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_taps')
    # ### end Alembic commands ###
