"""removed unnecessary website url attributes frm profile

Revision ID: 7ff6cd2ad8a9
Revises: 80a056474f75
Create Date: 2026-05-16 18:03:36.684737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff6cd2ad8a9'
down_revision: Union[str, Sequence[str], None] = '80a056474f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'x_url')
    op.drop_column('profiles', 'tiktok_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'facebook_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('facebook_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('tiktok_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('x_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
