"""added website url attributes to profile model

Revision ID: 80a056474f75
Revises: 3fc67527a489
Create Date: 2026-05-13 16:39:24.697143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a056474f75'
down_revision: Union[str, Sequence[str], None] = '3fc67527a489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('instagram_url', sa.String(length=2048), nullable=True))
    op.add_column('profiles', sa.Column('x_url', sa.String(length=2048), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=2048), nullable=True))
    op.add_column('profiles', sa.Column('facebook_url', sa.String(length=2048), nullable=True))
    op.add_column('profiles', sa.Column('tiktok_url', sa.String(length=2048), nullable=True))
    op.add_column('profiles', sa.Column('website_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'website_url')
    op.drop_column('profiles', 'tiktok_url')
    op.drop_column('profiles', 'facebook_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'x_url')
    op.drop_column('profiles', 'instagram_url')
    # ### end Alembic commands ###
