"""add subtitle and organization to profiles

Revision ID: 8da44ee1eb08
Revises: 8ea14315cee0
Create Date: 2026-09-18 01:34:45.901471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da44ee1eb08'
down_revision: Union[str, Sequence[str], None] = '8ea14315cee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('subtitle', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('organization', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'organization')
    op.drop_column('profiles', 'subtitle')
    # ### end Alembic commands ###
