"""add single primary contact partial unique index

Revision ID: 8ea14315cee0
Revises: 596dae8af91b
Create Date: 2026-09-18 01:05:44.674084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea14315cee0'
down_revision: Union[str, Sequence[str], None] = '596dae8af91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_profile_contacts_single_primary', 'profile_contacts', ['profile_id', 'contact_type'], unique=True, postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_contacts_single_primary', table_name='profile_contacts', postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###
