"""removed pointing_url from card model

Revision ID: 953d844114eb
Revises: cfacdfaddf78
Create Date: 2026-09-16 18:08:33.294169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953d844114eb'
down_revision: Union[str, Sequence[str], None] = 'cfacdfaddf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'pointing_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('pointing_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
