"""add display order to profile_links

Revision ID: 9b8965988c5d
Revises: ac5a5702c859
Create Date: 2026-06-24 15:36:11.470847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8965988c5d'
down_revision: Union[str, Sequence[str], None] = 'ac5a5702c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_links', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    
    op.alter_column("profile_links", "display_order", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_links', 'display_order')
    # ### end Alembic commands ###
