"""add label to profile links

Revision ID: ac5a5702c859
Revises: 55d8230f72aa
Create Date: 2026-06-09 22:16:42.165176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5a5702c859'
down_revision: Union[str, Sequence[str], None] = '55d8230f72aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_links', sa.Column('label', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_links', 'label')
    # ### end Alembic commands ###
