"""add beta feedback model

Revision ID: b01186dca9af
Revises: 541b87bf0083
Create Date: 2026-07-10 15:49:53.649583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01186dca9af'
down_revision: Union[str, Sequence[str], None] = '541b87bf0083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.Enum('bug', 'suggestion', 'other', name='feedbacktype'), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('page_url', sa.String(length=2048), nullable=False),
    sa.Column('feedback_description', sa.Text(), nullable=False),
    sa.Column('browser_info', sa.Text(), nullable=True),
    sa.Column('screen_size', sa.String(length=50), nullable=True),
    sa.Column('feedback_status', sa.Enum('open', 'in_progress', 'resolved', name='feedbackstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beta_feedback')
    # ### end Alembic commands ###
