"""added user_type attr to users model

Revision ID: b1be9ed753a6
Revises: cbafb17c6380
Create Date: 2026-07-29 14:20:35.330367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1be9ed753a6'
down_revision: Union[str, Sequence[str], None] = 'cbafb17c6380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type = sa.Enum('admin', 'user', 'system', name='usertype')
    user_type.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('user_type', user_type, nullable=False, server_default='user'))
    op.alter_column('users', 'user_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    user_type = sa.Enum('admin', 'user', 'system', name='usertype')
    user_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
