"""added version attribute to beta feedback

Revision ID: cbafb17c6380
Revises: b01186dca9af
Create Date: 2026-07-10 16:58:40.313936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbafb17c6380'
down_revision: Union[str, Sequence[str], None] = 'b01186dca9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beta_feedback', sa.Column('version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beta_feedback', 'version')
    # ### end Alembic commands ###
