"""added fk user_id to cards model

Revision ID: cfacdfaddf78
Revises: 515c5822d127
Create Date: 2026-09-16 17:03:52.769682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfacdfaddf78'
down_revision: Union[str, Sequence[str], None] = '515c5822d127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'cards_user_id_fkey', 'cards', 'users', ['user_id'], ['user_id'], ondelete='SET NULL'
    )
    op.create_index('ix_cards_user_id', 'cards', ['user_id'])
    # ### end Alembic commands ###

    op.execute("""
        UPDATE cards
        SET user_id = profiles.user_id
        FROM profiles
        WHERE cards.profile_id = profiles.profile_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cards_user_id', table_name='cards')
    op.drop_constraint('cards_user_id_fkey', 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###
