"""replaced is_active with card_status

Revision ID: f727c35c4bef
Revises: 1723f13e9261
Create Date: 2026-05-08 19:49:36.938969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f727c35c4bef'
down_revision: Union[str, Sequence[str], None] = '1723f13e9261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    card_status = sa.Enum(
    'inactive',
    'active',
    'deactivated',
    'lost',
    'disabled',
    name='card_status'
    )

    card_status.create(op.get_bind())
    
    op.add_column('cards', sa.Column('card_status', sa.Enum('inactive', 'active', 'deactivated', 'lost', 'disabled', name='card_status'), nullable=False))
    op.drop_column('cards', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('cards', 'card_status')
    # ### end Alembic commands ###
